// generated by Fast Light User Interface Designer (fluid) version 1.0302

#ifndef UserInterface_h
#define UserInterface_h

#include "main.h"
#include "TimePlot.h"
#include "BarPlot.h"
#include "WorkspacePlot.h"
#include "ForceSensor.h"
#include "MaglevControl.h"
#include "TimeHandler.h"

#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Choice.H>
#include <FL/Fl_Button.H>

class UserInterface
{
    public:
        /////////////////////////////////////////////////
        // Variables
        
        Fl_Double_Window *main_window;
        TimePlot *box_time;
        BarPlot *bar_force;
        WorkspacePlot *my_workspace;
        MaglevControl *my_maglev;
        ForceSensor *my_force;
        TimeHandler *my_timer;
        
        /////////////////////////////////////////////////
        // Functions
        
        UserInterface();
        ~UserInterface();
        void make_window();
        int start_controller();
        int begin_experiment();
        void readDesiredData(float* desired_data);
        
    private:
        /////////////////////////////////////////////////
        // Variables
        
        // Various Buttons and Combo Boxes
        Fl_Group *group_options;
        Fl_Choice *cmbTongue;
        Fl_Choice *cmbProduct;
        Fl_Choice *cmbHydration;
        Fl_Button *btnStartController;
        Fl_Button *btnTest;
        Fl_Button *btnForceSensor;
        
        /////////////////////////////////////////////////
        // Functions
        
        inline void cb_btnStartController_i(Fl_Button*, void*);
        static void cb_btnStartController(Fl_Button*, void*);
        inline void cb_btnTest_i(Fl_Button*, void*);
        static void cb_btnTest(Fl_Button*, void*);
        inline void cb_btnForceSensor_i(Fl_Button*, void*);
        static void cb_btnForceSensor(Fl_Button*, void*);
};

extern void display_force_reading(void * v);
extern void display_position_reading(void * v);

#endif
